language: java
sudo: required
jdk:
  - oraclejdk8
  - openjdk8
services:
  - docker
install:
 - chmod -R ugo+rwX .
script:
  - ./gradlew build --refresh-dependencies --rerun-tasks --recompile-scripts --info --continue --parallel