#!/bin/sh

SERVANT=graphouse

if [ "x$1" == "xupgrade" ]
then
    exit 0;
fi

echo Removing /usr/bin/$SERVANT.sh
rm -f /usr/bin/$SERVANT.sh

echo Removing $SERVANT from servant_list
cat /etc/yandex/servant_list | grep -v $SERVANT > /tmp/yandex-$$ && mv /tmp/yandex-$$ /etc/yandex/servant_list 

exit 0
