#!/bin/sh

case $1 in
configure)
	USER=graphouse
	GRAPHOUSE_ROOT=/opt/graphouse

	useradd ${USER} -r -g nogroup 2>/dev/null && echo "User ${USER} created"
	chown -R $USER:nogroup $GRAPHOUSE_ROOT

	ln -sf $GRAPHOUSE_ROOT/conf/ /etc/graphouse
	ln -sf $GRAPHOUSE_ROOT/log/ /var/log/graphouse
;;

abort-upgrade|abort-remove|abort-deconfigure)
;;
*)
	echo "postinst called with unknown argument \`$1'" >&2
;;

esac


exit 0

